spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flexi_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      enabled: false
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  rabbitmq:
    host: 192.168.1.91
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  type-aliases-package: com.flexi.app.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

flexi:
  jwt:
    secret: flexi_admin_secret_key
    expiration: 36000000
  upload:
    dir: /Users/renjianzhi/appdata/flexi-upload/images
    max-size: 10485760
  security:
    permit-paths: /asset/inventory/save-details
  multi-tenancy:
    enabled: true
    tenant-id-column: tenant_id
    ignore-tables:
      - sys_tenant
      - sys_config
mqtt:
  broker-url: tcp://192.168.1.91:1883
  username: kangcloud-anxingbao
  password: nutanix/4u
  client-id: my-springboot-client
  subscribe-topic: '#'